export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_PRODUCT_IN_CART = "DELETE_PRODUCT_IN_CART";
export const CHANGE_MASSAGE = "CHANGE_MASSAGE";
export const UPDATE_PRODUCT_IN_CART = "UPDATE_PRODUCT_IN_CART";
export const UPDATE_PRODUCT_INVENTORY = "UPDATE_PRODUCT_INVENTORY";
export const UPDATE_INVENTORY_WITH_DELETE = "UPDATE_INVENTORY_WITH_DELETE";
